# 图片访问
domain: "http://127.0.0.1:8080"

# gemini 自定义安全设置
google:
#  safes:
#    - category: HARM_CATEGORY_HARASSMENT
#      threshold: BLOCK_NONE

# 开启特殊标记增强 
flags: true

# 内调llm，用于绘图时文本转tags
llm:
  baseUrl: "http://127.0.0.1:8081"
  model: "bing"
  token: "xxx"

# coze 默认配置；；；内置配置经常变动，难以维护改为配置化。新增webSdk模式，但还未得知速率是否有限制？？？
#coze:
#  8k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  128k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  images:
#    botId: 114514
#    version: 9527
#    scene: 2

interpreter:
  baseUrl: http://127.0.0.1:8000
  useProxy: false
  echoCode: false

custom-llm:
  baseUrl: http://127.0.0.1:8080
  useProxy: false

# toolCall 默认配置化; 在 flags 关闭时也可用
toolCall:
  id: -1
  enabled: false
  tasks: false

# 图片放大，domain需要公网可访问的地址
# key请到https://bigjpg.com获取，每月30次免费
# 目前注册没有限制，可配置多个key轮询
#magnify:
#  - "xxx"

# 用于429限流时切换代理ip，proxies/xxx 为 策略组，names 为组内的线路名称 （clash需开启webapi）
# names 修改自己的节点
clash:
  url: http://127.0.0.1:7891/proxies/xxx
  names:
    - "英国"
    - "美国"
    - "日本"
    - "xxx"
